# Generated by Django 4.2.7 on 2023-12-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('hardness', models.FloatField()),
                ('solids', models.FloatField()),
                ('chloramines', models.FloatField()),
                ('sulfate', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('organic_carbon', models.FloatField()),
                ('trihalomethanes', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('potability', models.CharField(blank=True, max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
